// src/components/home.tsx
import { posts } from "src/signals";

export function Home() {
  return (
    <main>
      {posts.value.map((post) => (
        <a href={`/post/${post.fields.slug}`} target="_self">
          <section>
            <h2>{post.fields.title}</h2>
          </section>
        </a>
      ))}
    </main>
  );
}

// src/components/home.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { store } from "../store";
  import type { PostEntry } from "../types";

  let posts: Array<PostEntry> = [];

  const unsub = store.subscribe((props) => {
    posts = props.posts;
  });

  onDestroy(unsub);
</script>

<h1>hello, world</h1>

{#each posts as post}
  <section>
    <h2><a href={post.fields.slug}>{post.fields.title}</a></h2>
  </section>
{/each}
